# Generated by Django 3.1.7 on 2021-04-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210408_2356'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='backend_user',
        ),
    ]
