# Generated by Django 3.1.7 on 2021-04-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='backend_feedback',
        ),
    ]
